version: '3'

services:
  wiremock:
    image: wiremock/wiremock:2.30.1
    container_name: wiremock
    ports:
      - "8087:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
    networks:
      - mynetwork

  springboot-api:
    build:
      context: springboot-api
      dockerfile: Dockerfile
    container_name: springboot-api
    ports:
      - "8070:8070"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

