apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-api
spec:
  selector:
    matchLabels:
      app: springboot-api
  template:
    metadata:
      labels:
        app: springboot-api
    spec:
      containers:
      - name: springboot-api
        image: local-repo:/springboot-api:latest
        ports:
        - containerPort: 8090
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8090
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8090
          initialDelaySeconds: 15
          periodSeconds: 5
